// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PersonalFinanceTracker.Data;

#nullable disable

namespace PersonalFinanceTracker.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	[Migration("20260525210000_AddTranscriptsArchive")]
	partial class AddTranscriptsArchive
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
			modelBuilder
				.HasAnnotation("ProductVersion", "10.0.6")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);
		}
	}
}